### ISSUE TITLE
can not open

### ISSUE THREAD

**Issue by leohu1** [GrinningHermit/Vector-Explorer-Tool#4]
Traceback (most recent call last):
  File "C:/Users/leo/Desktop/Vector-Explorer-Tool-master/vector_explorer_tool.py", line 143, in <module>
    run()
  File "C:/Users/leo/Desktop/Vector-Explorer-Tool-master/vector_explorer_tool.py", line 128, in run
    with anki_vector.Robot(args.serial, enable_camera_feed=True, enable_custom_object_detection=True, enable_face_detection=True) as robot:
TypeError: __init__() got an unexpected keyword argument 'enable_camera_feed'

Process finished with exit code 1

**Comment by CozmoCyke** [comment]
I had the same error :-)
the 'enable_camera_feed' arg in Robot doesn't exist in the last SDK version (0.6.0) ! This parameter has been renamed into a function 'init_camera_feed()'  and move in camera instead. 

Try to change the code in 'vector_explorer_tool.py' by these lines

with anki_vector.Robot(args.serial, enable_custom_object_detection=True, enable_face_detection=True) as robot:
        global animation_list
        global active_viewer
        global os_info

        anki_vector.Robot.camera.init_camera_feed()

**Comment by GrinningHermit** [comment]
Fix has been pushed to master. This problem should no longer occur.

**Comment by adamjimenez** [comment]
just tried for the first time from a fresh install and works great
